-- Eliminar la base de datos en caso de que exista:
DROP DATABASE IF EXISTS tccontract;

-- Crear la base de datos
CREATE DATABASE tccontract CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Usar la base de datos creada
USE tccontract;

-- Creación de Tablas y Relaciones
CREATE TABLE ciudades (
  ciudadid int PRIMARY KEY AUTO_INCREMENT,
  nombre varchar(100),
  departamentoid int
);

CREATE TABLE departamentos (
  departamentoid int PRIMARY KEY AUTO_INCREMENT,
  nombre varchar(100)
);

CREATE TABLE empresas (
  empresaid char(3) PRIMARY KEY,
  nit bigint UNIQUE NOT NULL,
  nombre varchar(250),
  direccion varchar(100),
  www varchar(100),
  ciudadid int
);

CREATE TABLE factura (
  facturaid int PRIMARY KEY AUTO_INCREMENT,
  empresaid char(3),
  valorfact float,
  fechafact datetime,
  pagoestado bit
);

CREATE TABLE servicios (
  servid int PRIMARY KEY AUTO_INCREMENT,
  tiposerv varchar(20),
  caracteristicas longtext,
  valormes float
);

CREATE TABLE emprecontract (
  contratoid int PRIMARY KEY AUTO_INCREMENT,
  empresaid char(3),
  servid int,
  valorservicio float
);

CREATE TABLE pago (
  pagoid int PRIMARY KEY AUTO_INCREMENT,
  facturaid int,
  fechapago datetime,
  valorpago float
);

CREATE TABLE personas (
  personaid int PRIMARY KEY AUTO_INCREMENT,
  documento bigint UNIQUE NOT NULL,
  nombre varchar(250),
  email varchar(100),
  celular varchar(20),
  empresaid char(3)
);

CREATE TABLE roles (
  rolid char(3) PRIMARY KEY,
  nombre varchar(50),
  descripcion longtext,
  permisos varchar(255)
);

CREATE TABLE usuarios (
  usuarioid int PRIMARY KEY AUTO_INCREMENT,
  login varchar(7),
  pass varchar(20),
  personaid int,
  rolid char(3)
);

CREATE TABLE tiporeq (
  tiporeqid char(3) PRIMARY KEY,
  nombre varchar(20),
  descripcion longtext
);

CREATE TABLE requerimiento (
  reqid int PRIMARY KEY AUTO_INCREMENT,
  tiporeqid char(3),
  usuarioid int,
  fechareq timestamp,
  prioridad int,
  nombre varchar(100),
  email varchar(100),
  telefono varchar(20),
  observacion longtext
);

CREATE TABLE gestionreq (
  gestionreqid int PRIMARY KEY AUTO_INCREMENT,
  usuarioid int,
  fechagestion timestamp,
  resuelto bit,
  observacion longtext
);

-- Relaciones de tablas
ALTER TABLE ciudades ADD FOREIGN KEY (departamentoid) REFERENCES departamentos (departamentoid);
ALTER TABLE empresas ADD FOREIGN KEY (ciudadid) REFERENCES ciudades (ciudadid);
ALTER TABLE factura ADD FOREIGN KEY (empresaid) REFERENCES empresas (empresaid);
ALTER TABLE pago ADD FOREIGN KEY (facturaid) REFERENCES factura (facturaid);
ALTER TABLE personas ADD FOREIGN KEY (empresaid) REFERENCES empresas (empresaid);
ALTER TABLE usuarios ADD FOREIGN KEY (personaid) REFERENCES personas (personaid);
ALTER TABLE usuarios ADD FOREIGN KEY (rolid) REFERENCES roles (rolid);
ALTER TABLE requerimiento ADD FOREIGN KEY (tiporeqid) REFERENCES tiporeq (tiporeqid);
ALTER TABLE requerimiento ADD FOREIGN KEY (usuarioid) REFERENCES usuarios (usuarioid);
ALTER TABLE gestionreq ADD FOREIGN KEY (usuarioid) REFERENCES usuarios (usuarioid);
ALTER TABLE emprecontract ADD FOREIGN KEY (empresaid) REFERENCES empresas (empresaid);
ALTER TABLE emprecontract ADD FOREIGN KEY (servid) REFERENCES servicios (servid);
ALTER TABLE tiporeq MODIFY nombre VARCHAR(100);

-- Insertar data base
INSERT INTO departamentos (nombre) VALUES
('AMAZONAS'),
('ANTIOQUIA'),
('ARAUCA'),
('ARCHIPIELAGO DE SAN ANDRES'),
('ATLÁNTICO'),
('BOGOTÁ D.C.'),
('BOLIVAR'),
('BOYACÁ'),
('CALDAS'),
('CAQUETA'),
('CASANARE'),
('CAUCA'),
('CESAR'),
('CHOCO'),
('CORDOBA'),
('CUNDINAMARCA'),
('GUAINIA'),
('GUAVIARE'),
('HUILA'),
('LA GUAJIRA'),
('MAGDALENA'),
('META'),
('NARIÑO'),
('NORTE DE SANTANDER'),
('PUTUMAYO'),
('QUINDIO'),
('RISARALDA'),
('SANTANDER'),
('SUCRE'),
('TOLIMA'),
('VALLE DEL CAUCA'),
('VAUPES'),
('VICHADA');

INSERT INTO ciudades (nombre, departamentoid) VALUES
('EL ENCANTO', 1),
('LA CHORRERA', 1),
('LA PEDRERA', 1),
('LA VICTORIA', 1),
('LETICIA', 1),
('MIRITI - PARANÁ', 1),
('PUERTO ALEGRIA', 1),
('PUERTO ARICA', 1),
('PUERTO NARIÑO', 1),
('PUERTO SANTANDER', 1),
('TARAPACÁ', 1),
('CÁCERES', 2),
('CAUCASIA', 2),
('EL BAGRE', 2),
('NECHÍ', 2),
('TARAZÁ', 2),
('ZARAGOZA', 2),
('CARACOLÍ', 2),
('MACEO', 2),
('PUERTO BERRiO', 2),
('PUERTO NARE', 2),
('PUERTO TRIUNFO', 2),
('YONDÓ', 2),
('AMALFI', 2),
('ANORÍ', 2),
('CISNEROS', 2),
('REMEDIOS', 2),
('SAN ROQUE', 2),
('SANTO DOMINGO', 2),
('SEGOVIA', 2),
('VEGACHÍ', 2),
('YALÍ', 2),
('YOLOMBÓ', 2),
('ANGOSTURA', 2),
('BELMIRA', 2),
('BRICEÑO', 2),
('CAMPAMENTO', 2),
('CAROLINA', 2),
('DON MATiAS', 2),
('ENTRERRIOS', 2),
('GÓMEZ PLATA', 2),
('GUADALUPE', 2),
('ITUANGO', 2),
('SAN ANDRÉS', 2),
('SAN JOSÉ DE LA MONTAÑA', 2),
('SAN PEDRO', 2),
('SANTA ROSA de osos', 2),
('TOLEDO', 2),
('VALDIVIA', 2),
('YARUMAL', 2),
('ABRIAQUÍ', 2),
('ANZA', 2),
('ARMENIA', 2),
('BURITICÁ', 2),
('CAÑASGORDAS', 2),
('DABEIBA', 2),
('EBÉJICO', 2),
('FRONTINO', 2),
('GIRALDO', 2),
('HELICONIA', 2),
('LIBORINA', 2),
('OLAYA', 2),
('PEQUE', 2),
('SABANALARGA', 2),
('SAN JERÓNIMO', 2),
('SANTAFÉ DE ANTIOQUIA', 2),
('SOPETRaN', 2),
('URAMITA', 2),
('ABEJORRAL', 2),
('ALEJANDRÍA', 2),
('ARGELIA', 2),
('CARMEN DE VIBORAL', 2),
('COCORNÁ', 2),
('CONCEPCIÓN', 2),
('GRANADA', 2),
('GUARNE', 2),
('GUATAPE', 2),
('LA CEJA', 2),
('LA UNIÓN', 2),
('MARINILLA', 2),
('NARIÑO', 2),
('PEÑOL', 2),
('RETIRO', 2),
('RIONEGRO', 2),
('SAN CARLOS', 2),
('SAN FRANCISCO', 2),
('SAN LUIS', 2),
('SAN RAFAEL', 2),
('SAN VICENTE', 2),
('SANTUARIO', 2),
('SONSON', 2),
('AMAGa', 2),
('ANDES', 2),
('ANGELOPOLIS', 2),
('BETANIA', 2),
('BETULIA', 2),
('CAICEDO', 2),
('CARAMANTA', 2),
('CIUDAD BOLÍVAR', 2),
('CONCORDIA', 2),
('FREDONIA', 2),
('HISPANIA', 2),
('JARDÍN', 2),
('JERICÓ', 2),
('LA PINTADA', 2),
('MONTEBELLO', 2),
('PUEBLORRICO', 2),
('SALGAR', 2),
('SANTA BaRBARA', 2),
('TÁMESIS', 2),
('TARSO', 2),
('TITIRIBÍ', 2),
('URRAO', 2),
('VALPARAISO', 2),
('VENECIA', 2),
('APARTADÓ', 2),
('ARBOLETES', 2),
('CAREPA', 2),
('CHIGORODÓ', 2),
('MURINDÓ', 2),
('MUTATA', 2),
('NECOCLÍ', 2),
('SAN JUAN DE URABA', 2),
('SAN PEDRO DE URABA', 2),
('TURBO', 2),
('VIGÍA DEL FUERTE', 2),
('BARBOSA', 2),
('BELLO', 2),
('CALDAS', 2),
('COPACABANA', 2),
('ENVIGADO', 2),
('GIRARDOTA', 2),
('ITAGUI', 2),
('LA ESTRELLA', 2),
('MEDELLÍN', 2),
('SABANETA', 2),
('ARAUCA', 3),
('ARAUQUITA', 3),
('CRAVO NORTE', 3),
('FORTUL', 3),
('PUERTO RONDÓN', 3),
('SARAVENA', 3),
('TAME', 3),
('PROVIDENCIA Y SANTA CATALINA', 4),
('SAN ANDReS', 4),
('BARRANQUILLA', 5),
('GALAPA', 5),
('MALAMBO', 5),
('PUERTO COLOMBIA', 5),
('SOLEDAD', 5),
('CAMPO DE LA CRUZ', 5),
('CANDELARIA', 5),
('LURUACO', 5),
('MANATi', 5),
('REPELON', 5),
('SANTA LUCiA', 5),
('SUAN', 5),
('BARANOA', 5),
('PALMAR DE VARELA', 5),
('POLONUEVO', 5),
('PONEDERA', 5),
('Sabanagrande', 5),
('SABANALARGA', 5),
('Santo Tomas', 5),
('JUAN DE ACOSTA', 5),
('PIOJÓ', 5),
('TUBARA', 5),
('USIACURi', 5),
('BOGOTA D.C.', 6),
('CICUCO', 7),
('HATILLO DE LOBA', 7),
('MARGARITA', 7),
('MOMPÓS', 7),
('SAN FERNANDO', 7),
('TALAIGUA NUEVO', 7),
('ARJONA', 7),
('ARROYOHONDO', 7),
('CALAMAR', 7),
('CARTAGENA', 7),
('CLEMENCIA', 7),
('MAHATES', 7),
('SAN CRISTOBAL', 7),
('SAN ESTANISLAO', 7),
('SANTA CATALINA', 7),
('SANTA ROSA DE LIMA', 7),
('SOPLAVIENTO', 7),
('TURBACO', 7),
('TURBANA', 7),
('VILLANUEVA', 7),
('ALTOS DEL ROSARIO', 7),
('BARRANCO DE LOBA', 7),
('EL PEÑON', 7),
('REGIDOR', 7),
('RÍO VIEJO', 7),
('SAN MARTIN DE LOBA', 7),
('ARENAL', 7),
('CANTAGALLO', 7),
('MORALES', 7),
('SAN PABLO', 7),
('SANTA ROSA DEL SUR', 7),
('SIMITÍ', 7),
('ACHÍ', 7),
('MAGANGUÉ', 7),
('MONTECRISTO', 7),
('PINILLOS', 7),
('SAN JACINTO DEL CAUCA', 7),
('TIQUISIO', 7),
('CARMEN DE BOLÍVAR', 7),
('CÓRDOBA', 7),
('EL GUAMO', 7),
('MARÍA LA BAJA', 7),
('SAN JACINTO', 7),
('SAN JUAN NEPOMUCENO', 7),
('ZAMBRANO', 7),
('CHÍQUIZA', 8),
('CHIVATÁ', 8),
('CÓMBITA', 8),
('CUCAITA', 8),
('MOTAVITA', 8),
('OICATÁ', 8),
('SAMACÁ', 8),
('SIACHOQUE', 8),
('SORA', 8),
('SORACÁ', 8),
('SOTAQUIRÁ', 8),
('TOCA', 8),
('TUNJA', 8),
('TUTA', 8),
('VENTAQUEMADA', 8),
('CHISCAS', 8),
('CUBARÁ', 8),
('EL COCUY', 8),
('EL ESPINO', 8),
('GUACAMAYAS', 8),
('GÜICÁN', 8),
('PANQUEBA', 8),
('LABRANZAGRANDE', 8),
('PAJARITO', 8),
('PAYA', 8),
('PISBA', 8),
('BERBEO', 8),
('CAMPOHERMOSO', 8),
('MIRAFLORES', 8),
('PÁEZ', 8),
('SAN EDUARDO', 8),
('ZETAQUIRA', 8),
('BOYACÁ', 8),
('CIÉNEGA', 8),
('JENESANO', 8),
('NUEVO COLÓN', 8),
('RAMIRIQUÍ', 8),
('RONDÓN', 8),
('TIBANÁ', 8),
('TURMEQUÉ', 8),
('UMBITA', 8),
('VIRACACHÁ', 8),
('CHINAVITA', 8),
('GARAGOA', 8),
('MACANAL', 8),
('PACHAVITA', 8),
('SAN LUIS DE GACENO', 8),
('SANTA MARÍA', 8),
('BOAVITA', 8),
('COVARACHÍA', 8),
('LA UVITA', 8),
('SAN MATEO', 8),
('SATIVANORTE', 8),
('SATIVASUR', 8),
('SOATÁ', 8),
('SUSACÓN', 8),
('TIPACOQUE', 8),
('BRICEÑO', 8),
('BUENAVISTA', 8),
('CALDAS', 8),
('CHIQUINQUIRÁ', 8),
('COPER', 8),
('LA VICTORIA', 8),
('MARIPÍ', 8),
('MUZO', 8),
('OTANCHE', 8),
('PAUNA', 8),
('PUERTO BOYACa', 8),
('QUÍPAMA', 8),
('SABOYÁ', 8),
('SAN MIGUEL DE SEMA', 8),
('SAN PABLO BORBUR', 8),
('TUNUNGUÁ', 8),
('ALMEIDA', 8),
('CHIVOR', 8),
('GUATEQUE', 8),
('GUAYATÁ', 8),
('LA CAPILLA', 8),
('SOMONDOCO', 8),
('SUTATENZA', 8),
('TENZA', 8),
('ARCABUCO', 8),
('CHITARAQUE', 8),
('GACHANTIVÁ', 8),
('MONIQUIRÁ', 8),
('RÁQUIRA', 8),
('SÁCHICA', 8),
('SAN JOSÉ DE PARE', 8),
('SANTA SOFÍA', 8),
('SANTANA', 8),
('SUTAMARCHÁN', 8),
('TINJACÁ', 8),
('TOGÜÍ', 8),
('VILLA DE LEYVA', 8),
('AQUITANIA', 8),
('CUÍTIVA', 8),
('FIRAVITOBA', 8),
('GAMEZA', 8),
('IZA', 8),
('MONGUA', 8),
('MONGUÍ', 8),
('NOBSA', 8),
('PESCA', 8),
('SOGAMOSO', 8),
('TIBASOSA', 8),
('TÓPAGA', 8),
('TOTA', 8),
('BELÉN', 8),
('BUSBANZÁ', 8),
('CERINZA', 8),
('CORRALES', 8),
('DUITAMA', 8),
('FLORESTA', 8),
('PAIPA', 8),
('SAN ROSA VITERBO', 8),
('TUTAZÁ', 8),
('BETÉITIVA', 8),
('CHITA', 8),
('JERICÓ', 8),
('PAZ DE RÍO', 8),
('SOCHA', 8),
('SOCOTÁ', 8),
('TASCO', 8),
('FILADELFIA', 9),
('LA MERCED', 9),
('MARMATO', 9),
('RIOSUCIO', 9),
('SUPÍA', 9),
('MANZANARES', 9),
('MARQUETALIA', 9),
('MARULANDA', 9),
('PENSILVANIA', 9),
('ANSERMA', 9),
('BELALCÁZAR', 9),
('RISARALDA', 9),
('SAN JOSÉ', 9),
('VITERBO', 9),
('CHINCHINa', 9),
('MANIZALES', 9),
('NEIRA', 9),
('PALESTINA', 9),
('VILLAMARiA', 9),
('AGUADAS', 9),
('ARANZAZU', 9),
('PÁCORA', 9),
('SALAMINA', 9),
('LA DORADA', 9),
('NORCASIA', 9),
('SAMANÁ', 9),
('VICTORIA', 9),
('ALBANIA', 10),
('BELÉN DE LOS ANDAQUIES', 10),
('CARTAGENA DEL CHAIRÁ', 10),
('CURRILLO', 10),
('EL DONCELLO', 10),
('EL PAUJIL', 10),
('FLORENCIA', 10),
('LA MONTAÑITA', 10),
('MILaN', 10),
('MORELIA', 10),
('PUERTO RICO', 10),
('SAN JOSE DEL FRAGUA', 10),
('SAN VICENTE DEL CAGUÁN', 10),
('SOLANO', 10),
('SOLITA', 10),
('VALPARAISO', 10),
('AGUAZUL', 11),
('CHAMEZA', 11),
('HATO COROZAL', 11),
('LA SALINA', 11),
('MANÍ', 11),
('MONTERREY', 11),
('NUNCHÍA', 11),
('OROCUÉ', 11),
('PAZ DE ARIPORO', 11),
('PORE', 11),
('RECETOR', 11),
('SABANALARGA', 11),
('SÁCAMA', 11),
('SAN LUIS DE PALENQUE', 11),
('TÁMARA', 11),
('TAURAMENA', 11),
('TRINIDAD', 11),
('VILLANUEVA', 11),
('YOPAL', 11),
('CAJIBÍO', 12),
('EL TAMBO', 12),
('LA SIERRA', 12),
('MORALES', 12),
('PIENDAMO', 12),
('POPAYÁN', 12),
('ROSAS', 12),
('SOTARA', 12),
('TIMBIO', 12),
('BUENOS AIRES', 12),
('CALOTO', 12),
('CORINTO', 12),
('MIRANDA', 12),
('PADILLA', 12),
('PUERTO TEJADA', 12),
('SANTANDER DE QUILICHAO', 12),
('SUAREZ', 12),
('VILLA RICA', 12),
('GUAPI', 12),
('LOPEZ', 12),
('TIMBIQUI', 12),
('CALDONO', 12),
('INZÁ', 12),
('JAMBALO', 12),
('PAEZ', 12),
('PURACE', 12),
('Silvia', 12),
('TORIBIO', 12),
('TOTORO', 12),
('ALMAGUER', 12),
('ARGELIA', 12),
('BALBOA', 12),
('BOLÍVAR', 12),
('FLORENCIA', 12),
('LA VEGA', 12),
('MERCADERES', 12),
('PATIA', 12),
('PIAMONTE', 12),
('SAN SEBASTIAN', 12),
('SANTA ROSA', 12),
('SUCRE', 12),
('BECERRIL', 13),
('CHIMICHAGUA', 13),
('CHIRIGUANA', 13),
('CURUMANÍ', 13),
('LA JAGUA DE IBIRICO', 13),
('PAILITAS', 13),
('TAMALAMEQUE', 13),
('ASTREA', 13),
('BOSCONIA', 13),
('EL COPEY', 13),
('EL PASO', 13),
('AGUSTÍN CODAZZI', 13),
('LA PAZ', 13),
('MANAURE', 13),
('PUEBLO BELLO', 13),
('SAN DIEGO', 13),
('VALLEDUPAR', 13),
('AGUACHICA', 13),
('GAMARRA', 13),
('GONZÁLEZ', 13),
('LA GLORIA', 13),
('PELAYA', 13),
('RÍO DE ORO', 13),
('SAN ALBERTO', 13),
('SAN MARTÍN', 13),
('ATRATO', 14),
('BAGADÓ', 14),
('BOJAYA', 14),
('EL CARMEN DE ATRATO', 14),
('LLORÓ', 14),
('MEDIO ATRATO', 14),
('QUIBDÓ', 14),
('RIO QUITO', 14),
('ACANDÍ', 14),
('BELÉN DE BAJIRA', 14),
('CARMÉN DEL DARIÉN', 14),
('RIOSUCIO', 14),
('UNGUÍA', 14),
('BAHÍA SOLANO', 14),
('JURADÓ', 14),
('NUQUÍ', 14),
('ALTO BAUDÓ', 14),
('BAJO BAUDÓ', 14),
('El Litoral del San Juan', 14),
('MEDIO BAUDÓ', 14),
('CANTON DE SAN PABLO', 14),
('CERTEGUI', 14),
('CONDOTO', 14),
('ITSMINA', 14),
('MEDIO SAN JUAN', 14),
('NÓVITA', 14),
('RÍO FRÍO', 14),
('SAN JOSÉ DEL PALMAR', 14),
('SIPÍ', 14),
('TADÓ', 14),
('UNION PANAMERICANA', 14),
('TIERRALTA', 15),
('VALENCIA', 15),
('CHIMÁ', 15),
('COTORRA', 15),
('LORICA', 15),
('MOMIL', 15),
('PURÍSIMA', 15),
('MONTERÍA', 15),
('CANALETE', 15),
('LOS CÓRDOBAS', 15),
('MOÑITOS', 15),
('PUERTO ESCONDIDO', 15),
('SAN ANTERO', 15),
('SAN BERNARDO DEL VIENTO', 15),
('CHINÚ', 15),
('SAHAGÚN', 15),
('SAN ANDRÉS SOTAVENTO', 15),
('AYAPEL', 15),
('BUENAVISTA', 15),
('LA APARTADA', 15),
('MONTELÍBANO', 15),
('PLANETA RICA', 15),
('PUEBLO NUEVO', 15),
('PUERTO LIBERTADOR', 15),
('CERETÉ', 15),
('CIÉNAGA DE ORO', 15),
('SAN CARLOS', 15),
('SAN PELAYO', 15),
('CHOCONTÁ', 16),
('MACHETA', 16),
('MANTA', 16),
('SESQUILÉ', 16),
('SUESCA', 16),
('TIBIRITA', 16),
('VILLAPINZÓN', 16),
('AGUA DE DIOS', 16),
('GIRARDOT', 16),
('GUATAQUÍ', 16),
('JERUSALÉN', 16),
('NARIÑO', 16),
('NILO', 16),
('RICAURTE', 16),
('TOCAIMA', 16),
('CAPARRAPÍ', 16),
('GUADUAS', 16),
('PUERTO SALGAR', 16),
('ALBÁN', 16),
('LA PEÑA', 16),
('LA VEGA', 16),
('NIMAIMA', 16),
('NOCAIMA', 16),
('QUEBRADANEGRA', 16),
('SAN FRANCISCO', 16),
('SASAIMA', 16),
('SUPATÁ', 16),
('ÚTICA', 16),
('VERGARA', 16),
('VILLETA', 16),
('GACHALA', 16),
('GACHETA', 16),
('GAMA', 16),
('GUASCA', 16),
('GUATAVITA', 16),
('JUNÍN', 16),
('LA CALERA', 16),
('UBALÁ', 16),
('BELTRÁN', 16),
('BITUIMA', 16),
('CHAGUANÍ', 16),
('GUAYABAL DE SIQUIMA', 16),
('PULI', 16),
('SAN JUAN DE RÍO SECO', 16),
('VIANÍ', 16),
('MEDINA', 16),
('PARATEBUENO', 16),
('CAQUEZA', 16),
('CHIPAQUE', 16),
('CHOACHÍ', 16),
('FOMEQUE', 16),
('FOSCA', 16),
('GUAYABETAL', 16),
('GUTIÉRREZ', 16),
('QUETAME', 16),
('UBAQUE', 16),
('UNE', 16),
('EL PEÑÓN', 16),
('LA PALMA', 16),
('PACHO', 16),
('PAIME', 16),
('SAN CAYETANO', 16),
('TOPAIPI', 16),
('VILLAGOMEZ', 16),
('YACOPÍ', 16),
('CAJICÁ', 16),
('CHÍA', 16),
('COGUA', 16),
('GACHANCIPÁ', 16),
('NEMOCoN', 16),
('SOPÓ', 16),
('TABIO', 16),
('TOCANCIPÁ', 16),
('ZIPAQUIRÁ', 16),
('BOJACÁ', 16),
('COTA', 16),
('EL ROSAL', 16),
('FACATATIVÁ', 16),
('FUNZA', 16),
('MADRID', 16),
('MOSQUERA', 16),
('SUBACHOQUE', 16),
('TENJO', 16),
('ZIPACoN', 16),
('SIBATÉ', 16),
('SOACHA', 16),
('ARBELÁEZ', 16),
('CABRERA', 16),
('FUSAGASUGÁ', 16),
('GRANADA', 16),
('PANDI', 16),
('PASCA', 16),
('SAN BERNARDO', 16),
('SILVANIA', 16),
('TIBACUY', 16),
('VENECIA', 16),
('ANAPOIMA', 16),
('ANOLAIMA', 16),
('APULO', 16),
('CACHIPAY', 16),
('EL COLEGIO', 16),
('LA MESA', 16),
('QUIPILE', 16),
('SAN ANTONIO DE TEQUENDAMA', 16),
('TENA', 16),
('VIOTÁ', 16),
('CARMEN DE CARUPA', 16),
('CUCUNUBÁ', 16),
('FÚQUENE', 16),
('GUACHETÁ', 16),
('LENGUAZAQUE', 16),
('SIMIJACA', 16),
('SUSA', 16),
('SUTATAUSA', 16),
('TAUSA', 16),
('UBATE', 16),
('BARRANCO MINA', 17),
('CACAHUAL', 17),
('INÍRIDA', 17),
('LA GUADALUPE', 17),
('MAPIRIPaN', 17),
('MORICHAL', 17),
('PANA PANA', 17),
('PUERTO COLOMBIA', 17),
('SAN FELIPE', 17),
('CALAMAR', 18),
('EL RETORNO', 18),
('MIRAFLORES', 18),
('SAN JOSÉ DEL GUAVIARE', 18),
('AGRADO', 19),
('ALTAMIRA', 19),
('GARZÓN', 19),
('GIGANTE', 19),
('GUADALUPE', 19),
('PITAL', 19),
('SUAZA', 19),
('TARQUI', 19),
('AIPE', 19),
('ALGECIRAS', 19),
('BARAYA', 19),
('CAMPOALEGRE', 19),
('COLOMBIA', 19),
('HOBO', 19),
('IQUIRA', 19),
('NEIVA', 19),
('PALERMO', 19),
('RIVERA', 19),
('SANTA MARÍA', 19),
('TELLO', 19),
('TERUEL', 19),
('VILLAVIEJA', 19),
('YAGUARÁ', 19),
('LA ARGENTINA', 19),
('LA PLATA', 19),
('NÁTAGA', 19),
('PAICOL', 19),
('TESALIA', 19),
('ACEVEDO', 19),
('ELÍAS', 19),
('ISNOS', 19),
('OPORAPA', 19),
('PALESTINA', 19),
('PITALITO', 19),
('SALADOBLANCO', 19),
('SAN AGUSTÍN', 19),
('TIMANÁ', 19),
('ALBANIA', 20),
('DIBULLA', 20),
('MAICAO', 20),
('MANAURE', 20),
('RIOHACHA', 20),
('URIBIA', 20),
('BARRANCAS', 20),
('DISTRACCION', 20),
('EL MOLINO', 20),
('FONSECA', 20),
('HATONUEVO', 20),
('LA JAGUA DEL PILAR', 20),
('SAN JUAN DEL CESAR', 20),
('URUMITA', 20),
('VILLANUEVA', 20),
('ARIGUANÍ', 21),
('CHIBOLO', 21),
('NUEVA GRANADA', 21),
('PLATO', 21),
('SABANAS DE SAN ANGEL', 21),
('TENERIFE', 21),
('ALGARROBO', 21),
('ARACATACA', 21),
('CIÉNAGA', 21),
('EL RETEN', 21),
('FUNDACION', 21),
('PUEBLO VIEJO', 21),
('ZONA BANANERA', 21),
('CERRO SAN ANTONIO', 21),
('CONCORDIA', 21),
('EL PIÑON', 21),
('PEDRAZA', 21),
('PIVIJAY', 21),
('REMOLINO', 21),
('SALAMINA', 21),
('SITIONUEVO', 21),
('ZAPAYAN', 21),
('SANTA MARTA', 21),
('EL BANCO', 21),
('GUAMAL', 21),
('PIJIÑO DEL CARMEN', 21),
('SAN SEBASTIAN DE BUENAVISTA', 21),
('SAN ZENON', 21),
('SANTA ANA', 21),
('SANTA BARBARA DE PINTO', 21),
('EL CASTILLO', 22),
('EL DORADO', 22),
('FUENTE DE ORO', 22),
('GRANADA', 22),
('LA MACARENA', 22),
('LA URIBE', 22),
('LEJANÍAS', 22),
('MAPIRIPaN', 22),
('MESETAS', 22),
('PUERTO CONCORDIA', 22),
('PUERTO LLERAS', 22),
('PUERTO RICO', 22),
('SAN JUAN DE ARAMA', 22),
('VISTA HERMOSA', 22),
('VILLAVICENCIO', 22),
('ACACiAS', 22),
('BARRANCA DE UPIA', 22),
('CASTILLA LA NUEVA', 22),
('CUMARAL', 22),
('EL CALVARIO', 22),
('GUAMAL', 22),
('RESTREPO', 22),
('SAN CARLOS GUAROA', 22),
('SAN JUANITO', 22),
('SAN LUIS DE CUBARRAL', 22),
('SAN MARTÍN', 22),
('CABUYARO', 22),
('PUERTO GAITÁN', 22),
('PUERTO LoPEZ', 22),
('CHACHAGUI', 23),
('CONSACA', 23),
('EL PEÑOL', 23),
('EL TAMBO', 23),
('LA FLORIDA', 23),
('NARIÑO', 23),
('PASTO', 23),
('SANDONÁ', 23),
('TANGUA', 23),
('YACUANQUER', 23),
('ANCUYA', 23),
('GUAITARILLA', 23),
('LA LLANADA', 23),
('LINARES', 23),
('LOS ANDES', 23),
('MALLAMA', 23),
('OSPINA', 23),
('PROVIDENCIA', 23),
('RICAURTE', 23),
('SAMANIEGO', 23),
('SANTA CRUZ', 23),
('SAPUYES', 23),
('TUQUERRES', 23),
('BARBACOAS', 23),
('EL CHARCO', 23),
('FRANCISCO PIZARRO', 23),
('LA TOLA', 23),
('Magui', 23),
('MOSQUERA', 23),
('OLAYA HERRERA', 23),
('ROBERTO PAYAN', 23),
('SANTA BaRBARA', 23),
('TUMACO', 23),
('ALBAN', 23),
('ARBOLEDA', 23),
('BELEN', 23),
('BUESACO', 23),
('COLON', 23),
('CUMBITARA', 23),
('EL ROSARIO', 23),
('El Tablon de Gomez', 23),
('LA CRUZ', 23),
('LA UNION', 23),
('LEIVA', 23),
('POLICARPA', 23),
('SAN BERNARDO', 23),
('SAN LORENZO', 23),
('SAN PABLO', 23),
('SAN PEDRO DE CARTAGO', 23),
('TAMINANGO', 23),
('ALDANA', 23),
('CONTADERO', 23),
('CÓRDOBA', 23),
('CUASPUD', 23),
('CUMBAL', 23),
('FUNES', 23),
('GUACHUCAL', 23),
('GUALMATAN', 23),
('ILES', 23),
('IMUES', 23),
('IPIALES', 23),
('POTOSÍ', 23),
('PUERRES', 23),
('PUPIALES', 23),
('ARBOLEDAS', 24),
('CUCUTILLA', 24),
('GRAMALOTE', 24),
('LOURDES', 24),
('SALAZAR', 24),
('SANTIAGO', 24),
('VILLA CARO', 24),
('BUCARASICA', 24),
('EL TARRA', 24),
('SARDINATA', 24),
('TIBÚ', 24),
('ABREGO', 24),
('CACHIRÁ', 24),
('CONVENCIÓN', 24),
('EL CARMEN', 24),
('HACARÍ', 24),
('LA ESPERANZA', 24),
('LA PLAYA', 24),
('OCAÑA', 24),
('SAN CALIXTO', 24),
('TEORAMA', 24),
('CÚCUTA', 24),
('EL ZULIA', 24),
('LOS PATIOS', 24),
('PUERTO SANTANDER', 24),
('SAN CAYETANO', 24),
('VILLA DEL ROSARIO', 24),
('CÁCOTA', 24),
('CHITAGÁ', 24),
('MUTISCUA', 24),
('PAMPLONA', 24),
('PAMPLONITA', 24),
('SILOS', 24),
('BOCHALEMA', 24),
('CHINÁCOTA', 24),
('DURANIA', 24),
('HERRÁN', 24),
('LABATECA', 24),
('RAGONVALIA', 24),
('TOLEDO', 24),
('COLÓN', 25),
('MOCOA', 25),
('ORITO', 25),
('PUERTO ASIS', 25),
('PUERTO CAICEDO', 25),
('PUERTO GUZMAN', 25),
('PUERTO LEGUIZAMO', 25),
('SAN FRANCISCO', 25),
('SAN MIGUEL', 25),
('SANTIAGO', 25),
('SIBUNDOY', 25),
('VALLE DEL GUAMUEZ', 25),
('VILLA GARZON', 25),
('ARMENIA', 26),
('BUENAVISTA', 26),
('CALARCA', 26),
('CoRDOBA', 26),
('GeNOVA', 26),
('PIJAO', 26),
('FILANDIA', 26),
('SALENTO', 26),
('CIRCASIA', 26),
('LA TEBAIDA', 26),
('Montengro', 26),
('QUIMBAYA', 26),
('DOSQUEBRADAS', 27),
('LA VIRGINIA', 27),
('MARSELLA', 27),
('PEREIRA', 27),
('SANTA ROSA DE CABAL', 27),
('APÍA', 27),
('BALBOA', 27),
('BELÉN DE UMBRÍA', 27),
('GUÁTICA', 27),
('LA CELIA', 27),
('QUINCHiA', 27),
('SANTUARIO', 27),
('MISTRATÓ', 27),
('PUEBLO RICO', 27),
('CHIMA', 28),
('CONFINES', 28),
('CONTRATACIÓN', 28),
('EL GUACAMAYO', 28),
('GALÁN', 28),
('GAMBITA', 28),
('GUADALUPE', 28),
('GUAPOTÁ', 28),
('HATO', 28),
('OIBA', 28),
('PALMAR', 28),
('PALMAS DEL SOCORRO', 28),
('SANTA HELENA DEL OPÓN', 28),
('SIMACOTA', 28),
('SOCORRO', 28),
('SUAITA', 28),
('CAPITANEJO', 28),
('CARCASÍ', 28),
('CEPITÁ', 28),
('CERRITO', 28),
('CONCEPCIÓN', 28),
('ENCISO', 28),
('GUACA', 28),
('MACARAVITA', 28),
('MÁLAGA', 28),
('MOLAGAVITA', 28),
('SAN ANDRÉS', 28),
('SAN JOSÉ DE MIRANDA', 28),
('SAN MIGUEL', 28),
('ARATOCA', 28),
('BARICHARA', 28),
('CABRERA', 28),
('CHARALÁ', 28),
('COROMORO', 28),
('CURITÍ', 28),
('ENCINO', 28),
('JORDÁN', 28),
('MOGOTES', 28),
('OCAMONTE', 28),
('ONZAGA', 28),
('PÁRAMO', 28),
('PINCHOTE', 28),
('SAN GIL', 28),
('SAN JOAQUÍN', 28),
('VALLE DE SAN JOSÉ', 28),
('VILLANUEVA', 28),
('BARRANCABERMEJA', 28),
('BETULIA', 28),
('EL CARMEN DE CHUCURÍ', 28),
('PUERTO WILCHES', 28),
('SABANA DE TORRES', 28),
('SAN VICENTE DE CHUCURÍ', 28),
('ZAPATOCA', 28),
('BUCARAMANGA', 28),
('CALIFORNIA', 28),
('CHARTA', 28),
('EL PLAYÓN', 28),
('FLORIDABLANCA', 28),
('GIRÓN', 28),
('LEBRÍJA', 28),
('LOS SANTOS', 28),
('MATANZA', 28),
('PIEDECUESTA', 28),
('RIONEGRO', 28),
('SANTA BÁRBARA', 28),
('SURATA', 28),
('TONA', 28),
('VETAS', 28),
('AGUADA', 28),
('ALBANIA', 28),
('BARBOSA', 28),
('BOLÍVAR', 28),
('CHIPATÁ', 28),
('CIMITARRA', 28),
('EL PEÑÓN', 28),
('FLORIÁN', 28),
('GUAVATÁ', 28),
('GuEPSA', 28),
('JESÚS MARÍA', 28),
('LA BELLEZA', 28),
('LA PAZ', 28),
('LANDÁZURI', 28),
('PUENTE NACIONAL', 28),
('PUERTO PARRA', 28),
('SAN BENITO', 28),
('SUCRE', 28),
('VÉLEZ', 28),
('GUARANDA', 29),
('MAJAGUAL', 29),
('SUCRE', 29),
('CHALÁN', 29),
('COLOSO', 29),
('MORROA', 29),
('OVEJAS', 29),
('SINCELEJO', 29),
('COVEÑAS', 29),
('PALMITO', 29),
('SAN ONOFRE', 29),
('SANTIAGO DE TOLÚ', 29),
('TOLÚ VIEJO', 29),
('BUENAVISTA', 29),
('COROZAL', 29),
('EL ROBLE', 29),
('GALERAS', 29),
('LOS PALMITOS', 29),
('SAMPUÉS', 29),
('SAN JUAN BETULIA', 29),
('SAN PEDRO', 29),
('SINCÉ', 29),
('CAIMITO', 29),
('LA UNIÓN', 29),
('SAN BENITO ABAD', 29),
('SAN MARCOS', 29),
('AMBALEMA', 30),
('ARMERO', 30),
('FALAN', 30),
('FRESNO', 30),
('HONDA', 30),
('MARIQUITA', 30),
('PALOCABILDO', 30),
('CARMEN DE APICALÁ', 30),
('CUNDAY', 30),
('ICONONZO', 30),
('MELGAR', 30),
('VILLARRICA', 30),
('ATACO', 30),
('CHAPARRAL', 30),
('COYAIMA', 30),
('NATAGAIMA', 30),
('ORTEGA', 30),
('PLANADAS', 30),
('RIOBLANCO', 30),
('RONCESVALLES', 30),
('SAN ANTONIO', 30),
('ALVARADO', 30),
('ANZOÁTEGUI', 30),
('CAJAMARCA', 30),
('COELLO', 30),
('ESPINAL', 30),
('FLANDES', 30),
('IBAGUe', 30),
('PIEDRAS', 30),
('ROVIRA', 30),
('SAN LUIS', 30),
('VALLE DE SAN JUAN', 30),
('ALPUJARRA', 30),
('DOLORES', 30),
('GUAMO', 30),
('PRADO', 30),
('PURIFICACIÓN', 30),
('SALDAÑA', 30),
('SUÁREZ', 30),
('CASABIANCA', 30),
('HERVEO', 30),
('LeRIDA', 30),
('LiBANO', 30),
('MURILLO', 30),
('SANTA ISABEL', 30),
('VENADILLO', 30),
('VILLAHERMOSA', 30),
('ANDALUCÍA', 31),
('BUGA', 31),
('BUGALAGRANDE', 31),
('CALIMA', 31),
('EL CERRITO', 31),
('GINEBRA', 31),
('GUACARÍ', 31),
('RESTREPO', 31),
('RIOFRIO', 31),
('SAN PEDRO', 31),
('TRUJILLO', 31),
('TULUÁ', 31),
('YOTOCO', 31),
('ALCALa', 31),
('ANSERMANUEVO', 31),
('ARGELIA', 31),
('BOLÍVAR', 31),
('CARTAGO', 31),
('EL ÁGUILA', 31),
('EL CAIRO', 31),
('EL DOVIO', 31),
('LA UNIÓN', 31),
('LA VICTORIA', 31),
('OBANDO', 31),
('ROLDANILLO', 31),
('TORO', 31),
('ULLOA', 31),
('VERSALLES', 31),
('ZARZAL', 31),
('BUENAVENTURA', 31),
('CAICEDONIA', 31),
('SEVILLA', 31),
('CALI', 31),
('CANDELARIA', 31),
('DAGUA', 31),
('FLORIDA', 31),
('JAMUNDÍ', 31),
('LA CUMBRE', 31),
('PALMIRA', 31),
('PRADERA', 31),
('VIJES', 31),
('YUMBO', 31),
('CARURU', 32),
('MITÚ', 32),
('PACOA', 32),
('PAPUNAHUA', 32),
('TARAIRA', 32),
('YAVARATÉ', 32),
('CUMARIBO', 33),
('LA PRIMAVERA', 33),
('PUERTO CARREÑO', 33),
('SANTA ROSALÍA', 33);

INSERT INTO tiporeq (tiporeqid, nombre, descripcion) VALUES
('FPR','Falla en PRD', 'Fallas en el cambiente productivo'),
('FQS','Falla en QAS', 'Fallas en el ambiente de pruebas'),
('SOL','Solicitud de Servicio', 'Solicitudes generales'),
('MAN','Mantenimiento','Actualizaciones, depuraciones de data'),
('ASE','Asesoría','Solicitud de asesoría');

